Book store
Irirwanirira/book-store pull request #4
Opened 2022-11-16 11:27 UTC by Irirwanirira

## This Pr consists of:

- [ ] Changed the defaults state of my state
- [ ] Kept my state immutable 
- [ ] Imported Redux provider 
- [ ] Connected app to the redux store 
- [ ] Imported Redux use dispatch to dispatch in the project 

### Thank you for reviewing my project

2022-11-16 12:40 UTC, mckent05 requested changes
Hi @Irirwanirira,

# STATUS: CHANGES REQUIRED ♻️ ♻️  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/202182336-9b1ea629-b973-4ea1-8937-81361f67a2fc.gif)

## Highlights
- All linter checks are passing ✔️ 
- PR title and summary are descriptive 👏 👏 


## Required Changes ♻️
- Please remove all disabled linters in your code, it is important to remember that linters help us ensure that we write clean and maintainable code, I advise that you try to fix all linter issues 👍 👍 
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-16 12:40 UTC, mckent05 commented on src/components/Book.js
> +  console.log(book.id)
- In order to make your code clean and easily maintainable, it's advisable to remove `console.log()` in your code, I'd suggest you remove this 👍 👍

2022-11-16 12:40 UTC, mckent05 commented on src/components/InputForm.js
> +    }
- I currently cannot view the `title` of a newly added book, this is likely because in your `Books` array in the redux store you are using the `Book` property to store the title of the book, but when adding a new book, you are use the `title` property to store the title of the book, please fix this 🙏 🙏

2022-11-16 12:40 UTC, mckent05 commented on src/redux/books/Books.js
> +];
- Anytime I try adding a new book to this array, I have an error, this is likely because you are accessing the new book to be added wrongly in the reducer responsible for adding books, please fix this 🙏 🙏

2022-11-16 12:40 UTC, mckent05 commented on src/redux/books/Books.js
> +        state.filter((book) => book.id !== action.id.id),
- When I try to delete a book, all books are removed from the UI, this is not the expected behavior of the website. A likely cause for this is that you are filtering the state and returning it in an array. Note that `state.filter` returns an array. Please fix this 🙏

2022-11-16 13:55 UTC, Irirwanirira commented on src/components/Book.js
> +  console.log(book.id)
Thank you for your time

2022-11-16 23:56 UTC, Irirwanirira commented on src/redux/books/Books.js
> +        state.filter((book) => book.id !== action.id.id),
Thank you for your time

2022-11-16 23:56 UTC, Irirwanirira commented on src/redux/books/Books.js
> +];
Thank you for your time

2022-11-17 00:17 UTC, emmiiorji approved these changes
Hi @Irirwanirira, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://www.funimada.com/assets/images/cards/big/congrats-13.gif)

## Good Highlights✔

- Good design implementation
- Linter checks are passing
- Good commit messages
- Requested changes have been implemented


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-17 00:19 UTC, merged